/*
WHALE CHURN & REVENUE RECOVERY ANALYSIS

Objective:
- Identify high-value customers ('whales') contibuting the majority of revenue,
  detect churn risk, and assign targeted winback strategies to maximize revenue recovery.

Key Concepts:
- Pareto Analysis (80/20 rule)
- Customer Segmentation (Active, Urgent Winback, Lost Whale)
- Churned Revenue (last 12 months inactivity)
- Priority Ranking (NTILE bucketing)
- Experiment Design (Target vs Control group)
*/

-- PART 1: Whale Identification

CREATE TABLE the_whales AS
WITH customer_revenue AS (
    -- calculate the total lifetime revenue generated by each customer.
    SELECT 
        customerkey,
        SUM(net_revenue) AS lifetime_revenue
    FROM
        sales
    GROUP BY
        customerkey
),

cumulative_contribution AS (
    -- rank customers by revenue and compute cumulative contribution
    SELECT
        customerkey,
        lifetime_revenue,
        SUM(lifetime_revenue) OVER(
            ORDER BY lifetime_revenue DESC
        ) AS running_lifetime_revenue,
        SUM(lifetime_revenue) OVER() AS total_revenue,
        ROW_NUMBER() OVER(
            ORDER BY lifetime_revenue DESC
        ) AS customer_rank,
        COUNT(*) OVER() AS total_customer_count
    FROM
        customer_revenue  
)

SELECT
-- identify the percentage of customers responsible for 80% of total revenue (whales)
    customerkey,
    lifetime_revenue,
    100 * (running_lifetime_revenue / total_revenue) AS cumulative_revenue_pct,
    100 * (customer_rank :: FLOAT / total_customer_count) AS customer_percentage_rank,
    CASE
        WHEN (running_lifetime_revenue / total_revenue) <= 0.8
        THEN 'Top Revenue Drivers'
        ELSE 'Long Tail'
    END AS pareto_segment
FROM
    cumulative_contribution;


-- PART 2: Churn & Recovery Strategy

WITH max_orderdates AS (
    -- retrieve last purchase date for each customer
    SELECT
        customerkey,
        MAX(order_date) AS last_orderdate
    FROM
        sales
    GROUP BY 1
),

customer_segment AS (
    -- segment customers by inactivity duration
    SELECT
        t.customerkey,
        full_name,
        CASE
            WHEN DATE '2026-01-01' - last_orderdate BETWEEN 181 AND 540
                THEN 'Urgent Winback'
            WHEN DATE '2026-01-01' - last_orderdate >= 541
                THEN 'Lost Whale'
            ELSE 'Active Whale'
        END AS 
            retention_status,
        ROUND(lifetime_revenue :: numeric, 2) AS lifetime_revenue,
        SUM(
            CASE WHEN order_date >= last_orderdate - INTERVAL '12 Months'
                     THEN net_revenue 
                 ELSE 0 
            END) AS churned_revenue,
        DATE '2026-01-01' - last_orderdate AS days_silent
    FROM
        the_whales t
    INNER JOIN
        sales s ON t.customerkey = s.customerkey
    INNER JOIN
        customers c ON t.customerkey = c.customerkey
    INNER JOIN
        max_orderdates m ON t.customerkey = m.customerkey
    WHERE NOT
        pareto_segment = 'Long Tail'
    GROUP BY
        t.customerkey,
        full_name,
        retention_status,
        lifetime_revenue,
        days_silent
),

winback_strategy AS (
    -- assign winback strategy based on customer segment
    SELECT
        customerkey,
        full_name,
        retention_status,
        lifetime_revenue,
        churned_revenue,
        days_silent,
        CASE
            WHEN retention_status = 'Urgent Winback'
                THEN 'Personalized Outreach + Courtesy Gift'
            WHEN retention_status = 'Lost Whale'
                THEN 'Personalized Outreach + Tailored Reactivation Offer'
            ELSE 'No Action required'
        END AS 
            winback_strategy
    FROM
        customer_segment
    WHERE
        retention_status != 'Active Whale'
),

priority_bucket AS (
    -- rank customers by churned revenue using NTILE
    SELECT
        customerkey,
        full_name,
        retention_status,
        NTILE(3) OVER (
            PARTITION BY retention_status
            ORDER BY churned_revenue DESC
        ) AS bucket,
        lifetime_revenue,
        churned_revenue,
        days_silent,
        winback_strategy
    FROM
        winback_strategy
),

priority_tiers AS (
    -- map buckets into priority tiers (tier 1 - 3)
    SELECT
        customerkey,
        full_name,
        retention_status,
        CASE
            WHEN bucket = 1 THEN 'Tier 1'
            WHEN bucket = 2 THEN 'Tier 2'
            WHEN bucket = 3 THEN 'Tier 3'
        END AS priority_tier,
        lifetime_revenue,
        churned_revenue,
        days_silent,
        winback_strategy
    FROM
        priority_bucket
),

experiment_groups AS (
    -- split customers into target (80%) and control (20%) groups
    SELECT 
        customerkey,
        full_name,
        retention_status,
        priority_tier,
        lifetime_revenue,
        churned_revenue,
        days_silent,
        winback_strategy,
        CASE
            WHEN NTILE(5) OVER (
                PARTITION BY retention_status
                ORDER BY RANDOM()
            ) IN (1, 2, 3, 4) THEN 'Target Group'
            ELSE 'Control Group'
        END AS experiment_group
    FROM
        priority_tiers
)

-- output prioritized recovery list
SELECT *
FROM experiment_groups
ORDER BY retention_status, churned_revenue DESC; 













 







 